### ISSUE TITLE
Demos: Include blender's built in HDRIs?

### ISSUE THREAD

**Issue by setpixel** [gkjohnson/three-gpu-pathtracer#109]
Blender uses these HDRIs in its default world presets. They are CC0 and all from from HDRI Haven. They are a really good selection and I think it would be super cool if you include them as selectable in the demos where appropriate.

Also, I don't think you should blur environment maps by default :D Blurring softens the shadows, which can be a cool effect, but it's not the expected result of the environment map.

**Comment by gkjohnson** [comment]
I uploaded a set of HDRIs from Polyhaven to here which should be a better selection:

https://github.com/gkjohnson/3d-demo-data/tree/main/hdri

But I should probably download the 1k versions rather than the 2k versions for the sake of file size. If you want to make a PR into that repo and this one with HDRIs you like I'd be happy to get the demos upgraded!

> Also, I don't think you should blur environment maps by default :D Blurring softens the shadows, which can be a cool effect, but it's not the expected result of the environment map.

Yeah the reason they're blurred is because with the random tiny env map highlights cause the models to take _forever_ to resolve. Like hundreds of thousands or multiple millions of samples to get something that looks nice. Getting #4 working would help images resolve much more quickly with unblurred environment maps. Once that's in I'll change the demos to use unblurred environment lighting.

Here's a comparison of a blurred vs unblurred env map at 500 samples

| 0.35 blur | 0.0 blur |
|---|---|
| ![image](https://user-images.githubusercontent.com/734200/164861281-ab79debc-1534-4515-824e-19a65e3693e5.png) | ![image](https://user-images.githubusercontent.com/734200/164861336-386690db-d60b-471f-bb60-4c70c4e5b026.png) |

**Comment by gkjohnson** [comment]
A quick update on env map importance sampling. Here's how much more quickly it resolves with "sharp" environment maps now. The images show 20 samples.

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/734200/166346481-7f879cd7-476b-4a53-904a-2773f9be76c2.png) | ![image](https://user-images.githubusercontent.com/734200/166346489-f24fe827-8045-40e1-905f-4c1a357fab97.png) |

**Comment by setpixel** [comment]
Whoa - that is great! I can't wait to see it on other demos!

**Comment by setpixel** [comment]
At least on the demos linked from github, environment blur doesn't seem to work. Also: https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/materialBall.html#transmission the env map doesn't seem to be having an effect on the objects.

**Comment by gkjohnson** [comment]
Correct that was one sacrifice that had to be made -- "backgroundBlur" now just blurs the background. If you want a blurry env map it should be blurred ahead of time. I'm thinking at some point a utility could be provided to help blur the environment map as needed (see #124)

**Comment by gkjohnson** [comment]
It does -- I noticed that I forgot to revert a change to the demo this morning so I fixed it. I also added the ability to "blur" the environment map using mip maps but it's probably best to have a more robust solution like #124 in the long run.

**Comment by gkjohnson** [comment]
Added more env maps to the main demo:

![image](https://user-images.githubusercontent.com/734200/168731960-94cbaec2-c32a-4871-ade0-b4b260fb38ef.png)

![image](https://user-images.githubusercontent.com/734200/168731973-009a8b87-83bf-4b10-a78b-01d92f7622e8.png)

![image](https://user-images.githubusercontent.com/734200/168731985-960126f2-9b18-4033-8601-9a057e8e64d5.png)
