### ISSUE TITLE
Site stops before bvh generation

### ISSUE THREAD

**Issue by optimus007** [gkjohnson/three-gpu-pathtracer#122]
**Describe the bug**
Was trying to setup the path tracing on my gltf models.

Just to make things simple i'm using the same file from the examples folder
[html ](https://github.com/optimus007/portfolio/blob/main/PathTrace.html)
[js file](https://github.com/optimus007/portfolio/blob/main/PathTrace.js)
&
[github page](https://optimus007.github.io/portfolio/PathTrace.html)

it seems to be stopping at the lines
https://github.com/optimus007/portfolio/blob/42e9b55199189165cb2b632e7dd12a841f04a77c/PathTrace.js#L773-L780

**Platform:**

 - Device: [Desktop]
 - OS: [Windows
 - GPU: [NVidia 1650, Radeon ]
 - Browser: [Chrome, Firefox]
 - Three.js version: [r139]
 - Library version: [latest]

**Comment by gkjohnson** [comment]
It's likely because you are trying to load the worker from another origin (unpkg.com) - I'm not sure what can be done about this on the library side. You can either download the worker logic to your local project to run the worker or just switch the scene generator to use the synchronous version, instead:

```js
const generator = new PathTracingSceneWorker();
const result = await generator.generate( ... );

// to

const generator = new PathTracingSceneGenerator();
const result = generator.generate( ... );
```

See this SO answer for more info:

https://stackoverflow.com/questions/21913673/execute-web-worker-from-different-origin

**Comment by optimus007** [comment]
![path trace](https://user-images.githubusercontent.com/6885294/166194820-a9afae84-54a3-4b50-8cd8-4a64da225bd1.png)


added that change and removed generator.dispose() and it running!
