### ISSUE TITLE
More flexible EnvMapGenerator

### ISSUE THREAD

**Issue by samevision** [gkjohnson/three-gpu-pathtracer#155]
Hello again,

would it be possible that you customize the BlurredEnvMapGenerator to make it an EnvMapGenerator which allows not only to customize the blur but also the intensity and rotation? This way you can ensure that the IBL is the same with and without path tracing.

Many greetings

**Comment by gkjohnson** [comment]
Hello! I think this is something that more belongs in three.js as a request. Ie support envmap rotation or env intensity on the Scene object.

There are also other ways to work around rotation if you'd like them to match - such as rotating the scene and camera rather than the environment map itself.
