### ISSUE TITLE
Black screen on Android (Firefox and Chrome)

### ISSUE THREAD

**Issue by kefon** [gkjohnson/three-gpu-pathtracer#192]
I'm working on some creation using three-gpu-pathtracer, and it works flawlessly on desktop. But then I wanted to try it on my android mobile and only got a black screen (no render, but the GUI loads ok). After some remote debugging I tried to display your demo files (Material Test Orb, Physically Based Materials, Lego Models, etc.) on my mobile to compare, but I got the same result: black screen... Anyone can confirm?

First thing I could think of was testing if WebGL2 is enabled = YES.

I'm running the 0.04 npm version.
(should I try the latest files to see if the M1 fix works here?)

Platform:

 - Device: MOBILE (Huawei Mate 20 Pro)
 - OS: Android
 - Browser: Chrome and Firefox
 - Three.js version: 0.139.2
 - Library version: 0.0.4

Here are the logs from the "Material Test Orb" demo scene:
![Screenshot_2](https://user-images.githubusercontent.com/5464064/175178288-34678935-ce1e-4b6d-b8a9-6f13a8666b4b.jpg)

Here are the logs from my scene:
(I'm not sure why I'm getting the extra IOR error here... Have to look at it.)
![Screenshot_1](https://user-images.githubusercontent.com/5464064/175178557-b6be06b7-9158-4e36-86db-3d92f678d61a.jpg)

Thanks in advance!

**Comment by gkjohnson** [comment]
Without the device it's hard to recommend too much - we might need some help understanding the issue. If you could narrow down the issue by comment out some of the shader code - ie just reading one texture since that seems to be the core of the issue - that would help.

One thing that might help - from [this page](https://webglreport.com/?v=2) is the `OES_texture_float_linear` extension supported?

**Comment by RenderTool** [comment]
halfloat type
