### ISSUE TITLE
Add a viewer for PBR database materials

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#252]
https://twitter.com/80Level/status/1557041514798129152
https://physicallybased.info/
https://github.com/AntonPalmqvist/physically-based-api

Do the properties map directly to glTF properties?

- Provide a drop down list of material options from the site
- Possibly provide a side-by-side image view for comparison
- Similar to the [model viewer test page](https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/viewerTest.html#khronos-DragonAttenuation)
- Use the same environment map as in the examples

**Comment by AntonPalmqvist** [comment]
Happy to see this initiative!

Just wanted to give you an update on what I'm working on. You can see a very rough WIP here (with some things missing, and some broken): https://physicallybased.info/explorer/

- The functionality to get materials from the database is not there yet, but it's planned
- I'm waiting for the [USD Asset Working Group](https://github.com/usd-wg/assets) to release a standardized version of the render ball, mentioned here: https://github.com/AntonPalmqvist/physically-based-api/issues/5#issuecomment-1221480309
- One thing to note is that I'm using [react-three-gpu-pathtracer](https://github.com/pmndrs/react-three-gpu-pathtracer), so I'm a few versions behind since I'm dependent on the maintainer to update it to the latest from your repo at some point.
- The properties are not mapping directly to MeshPhysicalMaterial, with some things missing (such as [Specular Color](https://twitter.com/AntonPalmqvist/status/1569616022784843776)) and some named differently. The API is using the [Autodesk Standard Surface](https://autodesk.github.io/standard-surface/) way of naming things, for the most part

Thank you for the great work on the path tracer btw, it's amazing.
/Anton

**Comment by gkjohnson** [comment]
That's great to see! Looking forward to it coming along - let me know if you have any questions.

> I'm waiting for the [USD Asset Working Group](https://github.com/usd-wg/assets) to release a standardized version of the render ball:

This would be great. Is the material ball you're using now available to use? Along with the camera parameters used to render your test images? It would be great to be able to render a 1-to-1 side by side in an example page here to find differences in render quality and parameters.

> One thing to note is that I'm using [react-three-gpu-pathtracer](https://github.com/pmndrs/react-three-gpu-pathtracer), so I'm a few versions behind

Yeah it looks like it's still on v0.0.2. The next version of the project will include some good material sampling improvements so maybe once that's out we can ping the maintainer and ask if it's possible to upgrade.

> The properties are not mapping directly to MeshPhysicalMaterial, with some things missing (such as [Specular Color](https://twitter.com/AntonPalmqvist/status/1569616022784843776)) and some named differently

Once you're further along if you have a function that maps your properties to the three.js materials that would be nice to share so we can get a comparison viewer going.

**Comment by gkjohnson** [comment]
cc @FarazzShaikh v0.0.7 of the pathtracer has just been released - is it possible to get a new release of react-three-gpu-pathtracer so users like Anton can take advantage of the new features? I don't think there have been any dramatic API changes. Does it make sense to make three-gpu-pathtracer a peer dependency for that project?

**Comment by FarazzShaikh** [comment]
Yeah sure, I just haven’t had the time to update the project. I’ll look into it today but no promises
