### ISSUE TITLE
Shader compilation fails on Safari due to luminance function being undefined.

### ISSUE THREAD

**Issue by ikeough** [gkjohnson/three-gpu-pathtracer#352]
**Describe the bug**

After updating to the latest version, the console shows the following error when trying to render any scene using the path tracer. This did not happen with version 8.

Safari throws an exception during shader compilation, as seen below. Chrome throws no exception, but just doesn't render.

**Expected behavior**

The `luminance` function should be defined and no error should occur.

**Screenshots and Repro Model**

![image](https://user-images.githubusercontent.com/1139788/211171305-4407bd49-3776-42a4-8886-3fb76aa8702f.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - GPU: Radeon
 - Browser: Safari
 - Three.js version: 148
 - Library version: 11

**Comment by ikeough** [comment]
Interesting. The function was changed here: https://github.com/gkjohnson/three-gpu-pathtracer/commit/bd8f9df0fff30378fc39390910bf05154609f585.

**Comment by ikeough** [comment]
I can get past the failure if I change out this line of code in my app:
```
const rgbeLoader = new RGBELoader().setDataType(HalfFloatType)
```
And use the async version as shown in the examples here.
```
const texture = await new RGBELoader().loadAsync(`/static/environment/${envMapPath}`)
```
But then I get an all black rendering.

**Comment by gkjohnson** [comment]
Thanks for the report! I'm not able to reproduce on my M1 machine - so a couple questions:

- Which Mac are you on? 
- Is Safari up to date?
- Have you tried the latest development version in the repo after #350 has been merged?

> Interesting. The function was changed here: https://github.com/gkjohnson/three-gpu-pathtracer/commit/bd8f9df0fff30378fc39390910bf05154609f585. I can't find where luminance is defined.

The `luminance` function is defined in three.js' "common" shader chunk [here](https://github.com/mrdoob/three.js/blob/72416bb220c5fa34414ecfbc1c727360e5176b6d/src/renderers/shaders/ShaderChunk/common.glsl.js#L91-L99). If readding the original implementation and removing the common chunk fixes this then I'm happy to do that. Otherwise it might be necessary to git bisect until we find which commit broke things or reporting to Webkit.

**Comment by ikeough** [comment]
2017 Macbook Pro, Radeon Pro 555 GPU (I'm overdue for an upgrade :) )

After the initial post, I updated three, which may have resolved the initial error that it couldn't find the `luminance` function. The second error remains. With the latest I get fully transparent materials on Chrome and fully black on Safari. I'll try with the latest bits and see if that improves things.

**Comment by ikeough** [comment]
Tried with the latest bits from master. Same problem on Safari.

Without path tracing using only HDRI + lights:
![image](https://user-images.githubusercontent.com/1139788/211440103-a6f8c77e-b616-48c4-b4e5-6d7c7eca1f23.png)

With path tracing:
![image](https://user-images.githubusercontent.com/1139788/211440148-ff5cd59f-88ee-4dc9-98bf-6a273cd2e0c0.png)

**Comment by ikeough** [comment]
Closing this as it seems related to something we're doing with materials. Will re-open if I can find a meaningful root cause.
