### ISSUE TITLE
Can the noise during updates be reduced?

### ISSUE THREAD

**Issue by x1911** [gkjohnson/three-gpu-pathtracer#413]
I must say, this is a fantastic project, 

and I would like to use this library in my next game. 

However, I am wondering if there is a way to reduce noise 

in real-time rendering and make it more efficient.

Maybe like the game “Control”  ^ - ^

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/8219031/223701162-7e266078-8bda-4dc1-bb79-1a14a02dfd33.png">

The computer I am using is M2 Pro 16GB and it's not running smoothly at this setting.

**Comment by gkjohnson** [comment]
There is a [denoiser](https://github.com/gkjohnson/three-gpu-pathtracer#denoisematerial) in the project but in general this is designed to be a high fidelity path tracer comparable to Cycles in Blender rather than a real time one. There further improvements and optimizations that could be made but they are not an immediate priority for me. Feel free to take a look at some issues and contribute some new features if you'd like to, though.

**Comment by x1911** [comment]
Thank you for your response. 

So, this denoiser lib can be used in real-time rendering, right? 

I will try it out.

**Comment by gkjohnson** [comment]
> So, this denoiser lib can be used in real-time rendering, right?

I cannot make any promises about the quality and performance of the denoiser for real time purposes.
