### ISSUE TITLE
Error while loading a GLTF in index.js

### ISSUE THREAD

**Issue by PalashGarg19** [gkjohnson/three-gpu-pathtracer#445]
I am trying to load my [GLTF model](https://gist.githubusercontent.com/PalashGarg19/1b1343ae526e7d17c2f9d176060df447/raw/9cad9b681b2e5255d65ba66e9b877951c0eb6bf7/kitchen_template.gltf) by changing the url in **_index.js_** file, but when I run the index.html in browser i receive the following error. Can anyone help me with this error. I am able to load other GLTF models, but above mentioned GLTF is throwing error.
![Screenshot from 2023-06-21 15-35-58](https://github.com/gkjohnson/three-gpu-pathtracer/assets/108533092/daf07b1d-afde-4715-a986-34db95d089d7)

**Comment by gkjohnson** [comment]
The model loads just fine:

<img width="984" alt="image" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/734200/35a0e357-76eb-4f09-89eb-149d9c469423">

<img width="1098" alt="image" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/734200/6e320501-1694-4e87-8ec0-0fcfb515fa11">

Perhaps the issue was related to #463 depending on your platform. In the future please provide the information in the issue templates.
