### ISSUE TITLE
Are only DoubleSide materials currently supported?

### ISSUE THREAD

**Issue by samo-c** [gkjohnson/three-gpu-pathtracer#57]
Are only DoubleSide materials currently supported?  
I tried adding BackSide material to the model, which was rendered DoubleSide.

**Comment by gkjohnson** [comment]
Right now models are assumed to be doubled sided since things like transmission will require information about face sidedness and front and back sides to behave correctly. It's possible for material sidedness to be taken into account but I expect that double sidedness will remain the default until other features are complete.

What's your use case only rendering the back side model? Can you share the model? I'm just curious.

**Comment by samo-c** [comment]
Look
[gltf.zip](https://github.com/gkjohnson/three-gpu-pathtracer/files/8401530/gltf.zip)

You can try looking down from above and looking up from below.

In addition, directly replace the model in the demo project with this model, the material of the floor is not rendered?
