### ISSUE TITLE
Repeat, Center, Rotation Texture parameters are not supported 

### ISSUE THREAD

**Issue by sonygod** [gkjohnson/three-gpu-pathtracer#91]
is pathtracer not support uv mapping ?

![image](https://user-images.githubusercontent.com/748320/162663131-b240b5c5-ad8b-49bf-936c-05405b15318a.png)

![image](https://user-images.githubusercontent.com/748320/162663158-a935b19f-87b6-4d56-a0d5-9368d7f5dfca.png)

[testPathtracerblender.zip](https://github.com/gkjohnson/three-gpu-pathtracer/files/8460957/testPathtracerblender.zip)

[houseglb.zip](https://github.com/gkjohnson/three-gpu-pathtracer/files/8460959/houseglb.zip)

**Comment by gkjohnson** [comment]
UV mapping is supported but some texture parameters like repeat, center, and rotation are not fully supported since the textures must be written to a texture array. The repeat factor of your texture is set to (0.005, 0.005) which means only a small portion of the texture is written to the texture array.

I recommend keeping your texture repeat parameters in the range [0.0, 1.0] for now and updating your floor UVs to accommodate. Perhaps the extra parameters can be supported once #75 is addressed.

**Comment by bhouston** [comment]
I can put a $200 USD bounty on this issue for an accepted PR. Sponsored by Threekit.

**Comment by gkjohnson** [comment]
Great! @alvinalexander The following things need to happen at a high level:

- The [RenderTarget2DArray](https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/src/uniforms/RenderTarget2DArray.js) class needs to strip the texture transforms before rendering.
- The texture transforms (`center`, `rotation`, `repeat`) need to be stored in the [MaterialTextures](https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/src/uniforms/MaterialsTexture.js) definition.
- The UV transforms need to be applied in the shader before sampling the textures.

As far as I understand three.js only supports one set of UV transforms per material and takes one of the map UVs but I'm not sure what priority they are used with. I'd have to do some digging in three.js to find out.

Adding a UV Texture to a plane and rendering it with different UV offsets would be a good way to test. Let me know if you have any questions! Happy to provide pointers along the way if you want to start a draft PR.

**Comment by alvinalexander** [comment]
Thanks for the outline @gkjohnson !

Based on the above discussion I have narrowed it down to these parameters from the Three.js texture specification: 

- repeat: Vector2d, where x and y  > 0
- offset: Vector 2d where x and y in [0,1]
- wrapS: Clam, RepeatWrapping, MirroredRepeatWrapping
- wrapT: Clam, RepeatWrapping, MirroredRepeatWrapping
- center: Vector2d where x and y in [0, 1]
- rotation: in [0, 2*PI]

Is the goal for this PR to support all these parameters for all textures, or can we limit it to subset, say center, rotation, repeat and wrap[s|t] in [RepeatWrapping, Clamp] ? 

Also, when you say:
> * The [RenderTarget2DArray](https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/src/uniforms/RenderTarget2DArray.js) class needs to strip the texture transforms before rendering.

do you mean that these values must be reset to Three.js defaults before the textures are rendered to the array?

**Comment by gkjohnson** [comment]
The `repeat` (vec2), `offset` (vec2), `center` (vec2), and `rotation` (float) properties from [the Texture docs](https://threejs.org/docs/#api/en/textures/Texture) are what I'm looking at - that will be an additional 7 floats per texture for at least 6+ textures.

The "wrapS" and "wrapT" values are a bit complicated because we can only set one mode per render target array and all textures are packed into that one target. We could emulate the "clamp" behavior in code but maybe that can be a next PR.

> > The [RenderTarget2DArray](https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/src/uniforms/RenderTarget2DArray.js) class needs to strip the texture transforms before rendering.
>
> do you mean that these values must be reset to Three.js defaults before the textures are rendered to the array?

Right. At the moment the textures are being transformed before being written into the render target array which breaks when UVs outside of [ 0, 1 ].

So with @bhouston's suggestion to specify these coordinates per texture here's what this looks like now:
- The [RenderTarget2DArray](https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/src/uniforms/RenderTarget2DArray.js) class needs to strip the texture transforms before rendering.
- Add 12 new pixels (2 per texture) to the end of each [MaterialsTexture](https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/src/uniforms/MaterialsTexture.js) definition with the above values.
- Read each bit of texture info into the shader in [this function](https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/src/shader/shaderStructs.js#L55) and extend the MaterialStruct definition to have new texture transform fields. I think it would be cleanest to create a new `TextureTransform` struct to encapsulate all the definitions in if that makes sense.
- The UV transforms need to be applied in the shader before sampling the textures.

Support all texture transforms is definitely more robust but will require more texture sampling. We should be able to cut down on that per texture if the texture isn't being used, though. But lets get it working first!

**Comment by bhouston** [comment]
BTW I believe that this:
> The repeat (vec2), offset (vec2), center (vec2), and rotation (float)

Can simply be represented by a 3x3 matrix, but you only need the top 6 elements, because the last row/column is (0,0,1) always - so I would add that texture transform to the parameters, rather than these individual elements.

The ThreeJS Texture class always has the ability to return a matrix I believe that combines these all together:

https://threejs.org/docs/#api/en/textures/Texture.matrix

**Comment by alvinalexander** [comment]
Thanks @bhouston ! I was going to construct the UV transformation matrix inside the shader using those values but it's great to know that ThreeJS has a utility function for this. 

This is the approach I am considering : 
- Disable the UV transform before rendering inside https://github.com/gkjohnson/three-gpu-pathtracer/blob/33936d3eaad18064ba849b6bf4f85e6bc5256682/src/uniforms/RenderTarget2DArray.js#L38
- For each `Texture`, get  `Texture.matrix` an write the first two rows (6 floats) into the floatArray https://github.com/gkjohnson/three-gpu-pathtracer/blob/33936d3eaad18064ba849b6bf4f85e6bc5256682/src/uniforms/MaterialsTexture.js#L126
- Read the UV matrix items inside [readMaterialInfo](https://github.com/gkjohnson/three-gpu-pathtracer/blob/33936d3eaad18064ba849b6bf4f85e6bc5256682/src/shader/shaderStructs.js#L55) and construct a `mat3 uvTransformMat` 
- Apply transform before sampling textures.
