### ISSUE TITLE
Allowing the pathtracer to exclude parts or layers of the scene

### ISSUE THREAD

**Issue by drcmda** [gkjohnson/three-gpu-pathtracer#99]
for reference: https://twitter.com/0xca0a/status/1513780243911385090

**Comment by gkjohnson** [comment]
I think the two options are a stencil prepass that masks the area where you want path tracing to happen but due to stencil buffer limitations you'd wind up with aliasing around the edges. Another option is to perform that path tracing is a normal surface material that you apply to an individual geometry which is more like what the [ao material](https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/aoRender.html) demo does at the moment. I think the latter is probably the best option with something like a depth prepass to avoid the performance hit from path tracing hidden surfaces.

**Comment by drcmda** [comment]
sounds very promising!

**Comment by gkjohnson** [comment]
@drcmda v0.0.3 included the ability to use transparent backdrops and specify materials to be rendered as a "matte" which means rendering them transparent:

![image](https://user-images.githubusercontent.com/734200/170793893-fefdc7de-98d2-4146-9bb6-f4341fe4d330.png)

I haven't done too much performance testing but theoretically this should be more performant since objects aren't being rendered. Is this the kind of thing you're looking for? Of course the background can also be excluded entirely and this can be composited with something else:

![image](https://user-images.githubusercontent.com/734200/170794148-c64c8888-0fa8-41dd-b6f6-247e991fa49b.png)

**Comment by gkjohnson** [comment]
I think the matte feature should suit this use case for now and we can revisit if more is needed.
